### ISSUE TITLE
Bug: Admin Console: Received error after attempting to cancel job. [OSM]

### ISSUE THREAD

**Issue by avni** [iiab/iiab-admin-console#228] opened 2019-06-30 13:55 UTC
### Expected behavior and actual behavior.
Received error after attempting to cancel job. See image. 

### Steps to reproduce the problem.
Go to http://box.lan/admin/, Select "Utilities", Select "Display Job Status", Select a job to cancel, Click "Cancel Checked Jobs"; Tried selecting different jobs, all jobs, all cancelations failed.

### Specifications like the version of the IIAB, operating system version, or hardware details.
Macbook Pro 2.7 Ghz 8 GB Ram
Mac OS Sierra 10.12.6
Chrome Version 74.0.3729.169
Server: RPI 4B Buster Lite
IIAB: 7.0 pre-release

<img width="159" alt="image" src="https://user-images.githubusercontent.com/47825/60397659-378f3600-9b1d-11e9-87c4-96446cf265b3.png">

**Comment by tim-moody** [comment] 2019-06-30 14:12
was server rpi?

**Comment by avni** [comment] 2019-06-30 15:07
The initial job was adding osm content packs. Yes, server was RPI lite. Updating original entry.

**Comment by tim-moody** [comment] 2019-06-30 15:15
cancelling osm job causes python error:

`Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./iiab-cmdsrv", line 649, in cmd_proc_thread
    cmd_resp = cmd_handler(cmd_msg)
  File "./iiab-cmdsrv", line 765, in cmd_handler
    resp = avail_cmds[cmd](cmd_info)
  File "./iiab-cmdsrv", line 2242, in cancel_job
    job_id = int(cmd_info['cmd_args']['job_id'])
KeyError: 'job_id'
`

**Comment by tim-moody** [comment] 2019-06-30 15:39
looks like this is a really old one. thanks for catching

**Comment by tim-moody** [comment] 2019-06-30 16:16
the problem is on the front end, no job_id supplied

**Comment by tim-moody** [comment] 2019-06-30 17:06
hit the motherload on this one

**Comment by tim-moody** [comment] 2019-06-30 17:10
fixed in #230

**Comment by holta** [comment] 2019-06-30 18:15
@avni please confirm this is fixed, by testing after running the usual:
```
sudo su -

cd /opt/iiab/iiab-admin-console
git pull
./install
```

**Comment by holta** [comment] 2019-06-30 20:28
> @avni please confirm this is fixed, by testing after running the usual:
> 
> ```
> sudo su -
> 
> cd /opt/iiab/iiab-admin-console
> git pull
> ./install
> ```

@avni if you're updating existing an Map Pack (rather than installing fresh) please remember to follow these instructions:

https://github.com/iiab/iiab/wiki/IIAB-Maps#how-do-i-upgrade-an-iiab-map-pack

**Comment by avni** [comment] 2019-06-30 21:44
Confirmed this works now after following above instructions. Thank you!

**Closed** 2019-06-30 21:59 UTC
Labels: bug
